config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt\-BR/ do
    resources :rooms
    resources :users

    resource :confirmation, only: [:show]
#2 passo - rotas dos recursos, ações create, new e destroy
    resource :user_sessions, only: [:create, :new, :destroy]

    root "home#index"
  end

  get '/:locale' => 'home#index', locale: /en|pt\-BR/
  #root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\Z/

#Escopos nomeados(abreviação do comando de busca where)
  scope :confirmed, -> { where.not(confirmed_at: nil)}#scopo que retorna todos usuarios que confirmaram sua conta

  #9b passo - metodo que verifica email e senha
  def self.authenticate(email, password)
    user = confirmed.find_by(email: email)#Busca do usuario por email
    if user.present?#Usuario presente?
      user.authenticate(password)#Retornará o proprio objeto se a senha estiver correto, caso contrario retornara falso
    end
  end

  # def self.authenticate(email, password)
  #   confirmed.
  #   find_by(email, password).
  #   try(:authenticate, password)
  # end

  # def self.authenticate(email, password)
  #   confirmed.
  #   find_by(email, password)&.authenticate(password)
  #
  # end

  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, minimum: 10, allow_blank: false#tamanho de 30 caract e não pode ficar em branco
  validates_format_of :email, with: EMAIL_REGEXP

  has_secure_password

#calback p/ gerar o token
  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64 #numeros aleatorios
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]#Metodo que será executado antes das ações edit e update

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Signup.confirm_email(@user).deliver

      redirect_to @user,
                  notice: 'Cadastro criado com sucesso!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user,
      notice: 'Cadastro atualizado com sucesso!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.
      require(:user).
      permit(:email, :full_name, :location, :password,
             :password_confirmation, :bio)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
      #redirect_to user_path(current_user.id)
    end
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <%= t('.message') %>
  </div>
<% end %>

<%= form_for @user do |f| %>
<p>
  <%= f.label(:full_name) %><br />
  <%= f.text_field(:full_name) %>
  <%= error_tag(@user, :full_name) %>
</p>

<p>
  <%= f.label :location %><br />
  <%= f.text_field :location %>
  <%= error_tag @user, :location %>
</p>
<p>
  <%= f.label :email %><br />
  <%= f.text_field :email %>
  <%= error_tag @user, :email %>
</p>
<p>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
  <%= error_tag @user, :password %>
</p>
<p>
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
  <%= error_tag @user, :password_confirmation %>
</p>
<p>
  <%= f.label :bio %><br />
  <%= f.text_area :bio %>
  <%= error_tag @user, :bio %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('links.back_profile'), @user %>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h1><%= t('.title', user_name: @user.full_name) %></h1>

<ul>
  <li><%= t('.location', location: @user.location) %></li>
  <li><%= t('.bio', bio: @user.bio) %></li>
</ul>

<%= link_to t('links.edit_profile'), edit_user_path(@user) %> |
<%= link_to t('links.home'), root_path %>