config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt\-BR/ do
    resources :rooms
    resources :users

    resource :confirmation, only: [:show]
#2 passo - rotas dos recursos, ações create, new e destroy
    resource :user_sessions, only: [:create, :new, :destroy]

    root "home#index"
  end

  get '/:locale' => 'home#index', locale: /en|pt\-BR/
  #root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/room.rb
class Room < ApplicationRecord
  validates_presence_of :title, :location
  validates_length_of :description, minimum: 10, allow_blank: false, :message => "Atenção aos erros"

  def complete_name
    "#{title}, #{location}"
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
                          #apenas/só
  before_action :set_room, only: [ :show, :edit, :update, :destroy ]
  before_action :require_authentication,
    only: [:new, :edit, :create, :update, :destroy]

  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  #Exibir as solicitações do room solicitado
  def show
  end

  # GET /rooms/new
  # Exibir formulario de um novo room
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        NewRoom.confirm_room(@room, User.find_by(email: 'lucas@gmail.com')).deliver

        format.html { redirect_to room_url(@room), notice: t('flash.notice.room_created') }
        #format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: t('flash.notice.room_updated') }
        #format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use retornos de chamada para compartilhar configurações ou restrições comuns entre as ações.
    def set_room
      @room = Room.find(params[:id])
    end

    # Permitir apenas uma lista de parâmetros confiáveis.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> <%= t('.message') %></h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
    <%#= error_tag(@room, :title) %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
    <%#= error_tag(@room, :location) %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
    <%#= error_tag(@room, :description) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong><% t('.title') %></strong>
    <%= room.title %>
  </p>

  <p>
    <strong><% t('.location') %></strong>
    <%= room.location %>
  </p>

  <p>
    <strong><% t('.description') %></strong>
    <%= room.description %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to t('links.show_room'), @room %> |
  <%= link_to t('links.back_to_rooms'), rooms_path %>
</div>

app/views/rooms/index.html.erb
<% if user_signed_in? %>
  <%= current_user.full_name %>
<% end %>
<p style="color: green"><%= notice %></p>

<h1><%= t('.title') %></h1>

<div id="rooms">
  <% @rooms.each do |room| %>
  <div style= 'margin-bottom: 40px'>
    <%= render room %>
    <p>
      <%= link_to t('links.show_room'), room %>
    </p>
  </div>
  <% end %>
</div>

<%= link_to t('links.new_room'), new_room_path %><br>
<%= link_to t('links.home'), root_path %>

app/views/rooms/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to t('links.back_to_rooms'), rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to t('links.edit_room'), edit_room_path(@room) %> |
  <%= link_to t('links.back_to_rooms'), rooms_path %>

  <%= button_to t('links.delete'), @room, method: :delete %>
</div>