config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt\-BR/ do
    resources :rooms
    resources :users

    resource :confirmation, only: [:show]
#2 passo - rotas dos recursos, ações create, new e destroy
    resource :user_sessions, only: [:create, :new, :destroy]

    root "home#index"
  end

  get '/:locale' => 'home#index', locale: /en|pt\-BR/
  #root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %></li>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li>
      <%= link_to t('layout.my_profile'),
                  user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path,
                   data: { "turbo-method": :delete } %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.signup'), new_user_path %></li>
    <li>
      <%= link_to t('layout.signin'), new_user_sessions_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('layout.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <div id="header-wrap">
        <h1><%= link_to t('layout.colchonet_net'), root_path %></h1>
<!--Lógica p/ verificar se usuario tem autenticação e fazer a renderização p/ partial correta -->
        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>
      </div>
    </header>

    <div id="content">
      <% if notice.present? %>
        <p id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p id="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>